services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://app:apppass@postgres:5432/dti
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=your-secret-key-here-change-in-production
      - JWT_SECRET=tester
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
        - arbre
  postgres:
    image: 'postgres:16'
    volumes:
        - pg_data:/var/lib/postgresql/data
    environment:
        - POSTGRES_USER=app
        - POSTGRES_PASSWORD=apppass
        - POSTGRES_DB=dti
    restart: unless-stopped
    networks:
        - arbre
  
networks:
  arbre: 

volumes:
  pg_data: